### ISSUE TITLE
Feat: update correct binding for KV

### ISSUE THREAD

**Issue by bangank36** [0xSalik/R2-Worker-API#1]
## Summary
So I tried to implement this worker but it is not working as expected, turns out I need to do 2 things
- Bind the KV namespace in [Dashboard UI](https://developers.cloudflare.com/workers/platform/environment-variables/#environment-variables-via-the-dashboard)
   Bind the KV namespace in [wrangler](https://developers.cloudflare.com/workers/platform/environment-variables/#add-kv-namespaces-via-wrangler)
- Access the key using [binding value](https://developers.cloudflare.com/workers/runtime-apis/kv/#reading-key-value-pairs)
   ```
   export default {
      async fetch(request, env, ctx) {
        const value = await env.NAMESPACE.get("first-key");
    
        if (value === null) {
          return new Response("Value not found", { status: 404 });
        }
        return new Response(value);
      },
    };
   ```
## Solution
- Assume the `wrangler.toml` binding is
   ```
   [[kv_namespaces]]
  binding = "YOUR_KV_NAME_SPACE"
  id = "<kv-namespace-id>"
   ```
- Then access the key in code via
   ```
   const authKeySecret = await env.YOUR_KV_NAME_SPACE.get('AUTH_KEY_SECRET');
   ```
   
   @thesalikkhan please tell me if this make sense and it need to be updated the code, I'll make a PR for this

**Comment by 0xSalik** [comment]
Using a KV Namespace for the auth key isn't recommended since it's unencrypted. It should be stored as an encrypted env variable from the worker settings. You don't need to bind that in `wrangler.toml` since its already associated with the specific worker.
I made a mistake while writing the README, which is now corrected. Thank you for bringing this to my attention.
